openapi: 3.0.1
info:
  title: Chatvolt AI - Contacts API
  description: Endpoints for Contact management.
  termsOfService: http://chatvolt.ai/terms
  contact:
    email: support@chatvolt.ai
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://api.chatvolt.ai
tags:
  - name: contacts
paths:
  /contacts:
    get:
      tags:
        - contacts
      summary: List Contacts
      description: Retrieves a list of contacts with filtering and pagination.
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
          description: Number of records to skip for pagination.
        - in: query
          name: limit
          schema:
            type: integer
            default: 100
          description: Maximum number of records to return.
        - in: query
          name: search
          schema:
            type: string
          description: Search term for email, phone number, first name, or last name.
        - in: query
          name: tags
          schema:
            type: array
            items:
              type: string
          description: List of tags to filter by.
        - in: query
          name: crmScenario
          schema:
            type: string
          description: Filter by CRM Scenario ID.
        - in: query
          name: crmStep
          schema:
            type: string
          description: Filter by CRM Step ID.
        - in: query
          name: conversationStatus
          schema:
            type: string
            enum: [RESOLVED, UNRESOLVED, HUMAN_REQUESTED]
          description: Filter by conversation status.
        - in: query
          name: agent
          schema:
            type: string
          description: Filter by Agent ID.
        - in: query
          name: priority
          schema:
            type: string
            enum: [LOW, MEDIUM, HIGH]
          description: Filter by conversation priority.
        - in: query
          name: startDate
          schema:
            type: string
            format: date-time
          description: Filter contacts created on or after this date.
        - in: query
          name: endDate
          schema:
            type: string
            format: date-time
          description: Filter contacts created on or before this date.
        - in: query
          name: hasEmail
          schema:
            type: boolean
          description: Filter contacts that have an email address.
        - in: query
          name: hasPhone
          schema:
            type: boolean
          description: Filter contacts that have a phone number.
        - in: query
          name: channel
          schema:
            type: string
            enum: [website, dashboard, whatsapp, zapi, telegram, instagramDm]
          description: Filter by conversation channel.
      responses:
        '200':
          description: A paginated list of contacts.
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contact'
                  count:
                    type: integer
                    example: 42
    post:
      tags:
        - contacts
      summary: Create or Update a Contact
      description: Creates a new contact, or updates an existing one if an ID is provided in the body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactPayload'
      responses:
        '200':
          description: The created or updated contact.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
  /contacts/{id}:
    delete:
      tags:
        - contacts
      summary: Delete a Contact
      description: Deletes a contact by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the contact to delete.
      responses:
        '200':
          description: Contact deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Contact deleted successfully.'
        '400':
          description: Invalid ID supplied.
        '404':
          description: Contact not found.
components:
  schemas:
    Contact:
      type: object
      properties:
        id:
          type: string
          format: cuid
        organizationId:
          type: string
          format: cuid
        email:
          type: string
          format: email
          nullable: true
        phoneNumber:
          type: string
          nullable: true
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        externalId:
          type: string
          nullable: true
        picture:
          type: string
          nullable: true
        metadata:
          type: object
          additionalProperties: true
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    ContactPayload:
      type: object
      properties:
        id:
          type: string
          format: cuid
          nullable: true
          description: Include the ID to update an existing contact. Omit to create a new one.
        email:
          type: string
          format: email
          nullable: true
        phoneNumber:
          type: string
          nullable: true
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        externalId:
          type: string
          nullable: true
        picture:
          type: string
          nullable: true
        metadata:
          type: object
          additionalProperties: true
          nullable: true
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []