openapi: 3.0.1
info:
  title: Chatvolt AI - Mercado Livre API
  description: Endpoints for integration with Mercado Livre.
  termsOfService: http://chatvolt.ai/terms
  contact:
    email: support@chatvolt.ai
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://api.chatvolt.ai
tags:
  - name: mercadolivre
paths:
  /mercadolivre/get-products:
    get:
      tags:
        - mercadolivre
      summary: Get Mercado Livre Products
      description: Retrieves a list of products from Mercado Livre, with optional fuzzy search filtering.
      parameters:
        - in: query
          name: agentId
          required: true
          schema:
            type: string
          description: The ID of the agent.
        - in: query
          name: query
          schema:
            type: string
          description: The search query for fuzzy search.
        - in: query
          name: threshold
          schema:
            type: number
            format: float
            default: 0.3
          description: The threshold for fuzzy search.
        - in: query
          name: maxResults
          schema:
            type: integer
          description: The maximum number of results to return.
        - in: query
          name: caseSensitive
          schema:
            type: boolean
            default: false
          description: Whether the search should be case-sensitive.
        - in: query
          name: sortByRelevance
          schema:
            type: boolean
            default: true
          description: Whether to sort the results by relevance.
        - in: query
          name: partialMatch
          schema:
            type: boolean
            default: true
          description: Whether to allow partial matches.
        - in: query
          name: typoTolerance
          schema:
            type: integer
            default: 1
          description: The typo tolerance for fuzzy search.
      responses:
        '200':
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MercadoLivreProduct'
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized.
        '404':
          description: Not found.
components:
  schemas:
    MercadoLivreProduct:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        currency_id:
          type: string
        condition:
          type: string
        permalink:
          type: string
        thumbnail:
          type: string
        pictures:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              url:
                type: string
        available_quantity:
          type: integer
        sold_quantity:
          type: integer
        shipping:
          type: object
          properties:
            free_shipping:
              type: boolean
            logistic_type:
              type: string
        attributes:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string
        warranty:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []